### ISSUE TITLE
documents

### ISSUE THREAD

**Issue by superboys2017** [nickurt/laravel-oxxa#1]
do you have a documents whit a tutorial how to use this

**Comment by nickurt** [comment]
Hi Superboys2017,

It's still very basic/wip and I don't think I will continue to improve it since we stopped using with Oxxa last year.

Only 'parts' of [Domains](https://github.com/nickurt/laravel-oxxa/blob/417d41033dea28a3162ebcae10132ff382662a48/src/Api/Domains.php)/[Funds](https://github.com/nickurt/laravel-oxxa/blob/417d41033dea28a3162ebcae10132ff382662a48/src/Api/Funds.php)/[Identities](https://github.com/nickurt/laravel-oxxa/blob/417d41033dea28a3162ebcae10132ff382662a48/src/Api/Identities.php) are included, based on the documentation from [Oxxa](https://www.oxxa.com/domeinnamen/api).

You can use it like this;

```php
Oxxa::domains()->check(array $params);
Oxxa::domains()->list(array $params);

Oxxa::identities()->list(array $params);

// etc
```

**Comment by superboys2017** [comment]
so this app does not work 100% nor does it have everything there is there a way to fix that i am not so good,
or can you explain how to make something like that

**Comment by nickurt** [comment]
Actually it's just a simple wrapper for the Oxxa API-commands defined in their documentation.

**Comment by superboys2017** [comment]
but I can also just redirect the user to the url from the api?

**Comment by nickurt** [comment]
What url?

**Comment by superboys2017** [comment]
![image](https://user-images.githubusercontent.com/40305210/87294082-80851300-c503-11ea-9128-3c338bb5f171.png)
this or do I say something very stupid because I have never really processed with api

**Comment by nickurt** [comment]
No, this will made by the 'request' function and will merge the command and (optional) params

**Comment by superboys2017** [comment]
is there a Dutch tutorial for it, I don't understand
